//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteDijital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class footermessage
    {
        public long id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string footerexplanation { get; set; }
        public Nullable<long> isaktif { get; set; }
        public Nullable<System.DateTime> messagetime { get; set; }
    }
}
