//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteDijital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelancer
    {
        public long id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string gsm { get; set; }
        public string websiteurl { get; set; }
        public Nullable<long> jobid { get; set; }
        public string jobexplanation { get; set; }
        public string userphotourl { get; set; }
        public string city { get; set; }
        public string explanation { get; set; }
        public Nullable<long> isaktif { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual FreelanceJob FreelanceJob { get; set; }
    }
}
