//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteDijital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class posttable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posttable()
        {
            this.comenttables = new HashSet<comenttable>();
        }
    
        public long id { get; set; }
        public string photourl { get; set; }
        public Nullable<long> categoryid { get; set; }
        public string description { get; set; }
        public string hashtags { get; set; }
        public Nullable<long> userid { get; set; }
        public string title { get; set; }
        public string postcontent { get; set; }
        public string spottext { get; set; }
        public Nullable<long> views { get; set; }
        public Nullable<long> postlike { get; set; }
        public Nullable<long> postdislike { get; set; }
        public Nullable<System.DateTime> possttime { get; set; }
        public string posturl { get; set; }
        public Nullable<long> isaktif { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comenttable> comenttables { get; set; }
        public virtual usertable usertable { get; set; }
    }
}
