//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteDijital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTable()
        {
            this.TaskTables = new HashSet<TaskTable>();
        }
    
        public long id { get; set; }
        public string projectname { get; set; }
        public Nullable<long> projectstatus { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<long> creatorid { get; set; }
    
        public virtual projectstatu projectstatu { get; set; }
        public virtual usertable usertable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTable> TaskTables { get; set; }
    }
}
