//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteDijital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsibletable
    {
        public long id { get; set; }
        public Nullable<long> taskid { get; set; }
        public Nullable<long> responsibleid { get; set; }
    
        public virtual TaskTable TaskTable { get; set; }
    }
}
