//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArteDijital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usertable()
        {
            this.comenttables = new HashSet<comenttable>();
            this.posttables = new HashSet<posttable>();
            this.ProjectTables = new HashSet<ProjectTable>();
            this.TaskTables = new HashSet<TaskTable>();
        }
    
        public long id { get; set; }
        public string username { get; set; }
        public string usersurname { get; set; }
        public string useremail { get; set; }
        public string userpassword { get; set; }
        public string userphotourl { get; set; }
        public string usernick { get; set; }
        public Nullable<long> userauthorityID { get; set; }
        public Nullable<long> isaktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comenttable> comenttables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<posttable> posttables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTable> ProjectTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTable> TaskTables { get; set; }
        public virtual userrole userrole { get; set; }
    }
}
